### ISSUE TITLE
v4l2/capability.go:48:33: could not determine kind of name for C.V4L2_CAP_IO_MC

### ISSUE THREAD

**Issue by wubigo** [edgexfoundry-holding/device-usb-camera#10]
[https://github.com/vladimirvivien/go4vl/issues/17](https://github.com/vladimirvivien/go4vl/issues/17)

**Comment by cloudxxx8** [comment]
@FelixTing please help see whether it is easy to fix and open the PR in https://github.com/vladimirvivien/go4vl if needed

**Comment by surajitx-pal** [comment]
Logitech C270 UBS camera

**Comment by FelixTing** [comment]
The error might be relevant to Linux kernel version.

There is an open issue https://github.com/vladimirvivien/go4vl/issues/13 related to this.
The author of go4vl says that the minimum kernel version supported is 5.10.x and up. However, I can build binary successfully on 5.10.0 but fail on 5.13.0. Further investigation is needed...

**Comment by wubigo** [comment]
reporting error even kernel update to 

```
 uname -r
5.10.5-051005-generic
```

reinstall  /usr/include/linux/videodev2.h

```
apt install --reinstall linux-libc-dev
```

**Comment by wubigo** [comment]
sudo dpkg -i linux-libc-dev_5.10.0-14.15_amd64.deb
