### ISSUE TITLE
Consul settings Discovery-Interval changes to 30s - but discovery command not triggering at every on 30s interval.

### ISSUE THREAD

**Issue by surajitx-pal** [edgexfoundry-holding/device-usb-camera#109]
# 🐞 Bug Report

All services are up & running, Discovery/Interval - time change to 30s through consul, and connected an USB camera, wait for more than 30s but new usb camera not discovering.
Note : only works after execution discovery command manually. No log information for discovery command after 30s waiting.

**Comment by surajitx-pal** [comment]
- All services are up & running, Discovery/Interval - time change to 30s through consul, and connected an USB camera, wait for more than 30s but new usb camera not discovering.
Note : only works after execution discovery command manually. No log information for discovery command after 30s waiting.

**Comment by lenny-goodell** [comment]
@surajitx-pal , are you restarting the device service after you change the interval in Consul?
This setting is not under the Writable section so it is not handled dynamically and the service must be restated for the change to take effect.

**Comment by surajitx-pal** [comment]
I didn't restart the service.
