### ISSUE TITLE
Missing steps in general usage documentation

### ISSUE THREAD

**Issue by ajcasagrande** [edgexfoundry-holding/device-usb-camera#169]
# 📚 Docs or Wiki Bug Report

### Description [**REQUIRED**]

  I did the steps you suggested to resolve the error and the “make build” and “make docker” succeeded.  However, https://github.com/edgexfoundry/device-usb-camera/blob/main/docs/general-usage.md then suggests the following:

Run device-usb-camera

Docker
For non secure mode
o   make gen ds-usb-camera no-secty

For secure mode
o   make gen ds-usb-camera

Docker Compose start command
```
docker-compose -p edgex up -d
```
 

When I tried either of the first two, it reports:

 
```
Make: *** No rule to make target ‘gen’.  Stop.
```
 

I looked through the Makefile and there is not a target gen, so not sure if there was a step I missed that configured the Makefile to have a gen: target or if this is an error in the instructions.

### What's the affected URL? [**REQUIRED**]
https://github.com/edgexfoundry/device-usb-camera/blob/main/docs/general-usage.md#run-device-usb-camera

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by lenny-goodell** [comment]
@ajcasagrande , is this still an issue with latest docs moved to edgex-docs?

**Comment by presatish** [comment]
Closing this as the recent docs https://docs.edgexfoundry.org/3.0/microservices/device/supported/device-usb-camera/walkthrough/deployment/ do not have the above mentioned commands.
