### ISSUE TITLE
Upgrade the go4vl from 0.0.2 to 0.0.5

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry-holding/device-usb-camera#207]
# 🚀 Feature Request

### Description [**REQUIRED**]
The new go4vl has fixed some issues, and we should upgrade it with some proper tests

related to https://github.com/edgexfoundry/device-usb-camera/pull/99

**Comment by lenny-goodell** [comment]
@ajcasagrande , @presatish 0.0.5 was merged via dependabot PR. 
Can we close this issue or do we think there will be issues moving forward with 0.0.5  and later versions?

**Comment by presatish** [comment]
> @ajcasagrande , @presatish 0.0.5 was merged via dependabot PR. Can we close this issue or do we think there will be issues moving forward with 0.0.5 and later versions?

@lenny-intel I think it should be fine to be closed.

**Comment by lenny-goodell** [comment]
Already using go4vl  0.0.5 . Closing issue
