### ISSUE TITLE
Project `aler9/rtsp-simple-server` is now `bluenviron/mediamtx`

### ISSUE THREAD

**Issue by farshidtz** [edgexfoundry-holding/device-usb-camera#272]
The RTSP Simple Server project has been renamed and moved to another Github account.

https://github.com/aler9/rtsp-simple-server now redirects to https://github.com/bluenviron/mediamtx

The docker images are still maintained [here](https://hub.docker.com/r/aler9/rtsp-simple-server/tags) but I don't know for how long this will continue. The new image name is [bluenviron/mediamtx](https://hub.docker.com/r/bluenviron/mediamtx)

At least, the configuration file name has been changed and there is now a new RTSP Auth Web Server (given this error message: `RTSP Auth Web server failed: listen tcp 127.0.0.1:8000: bind: address already in use`)
Need to look into other possible changes.

**Comment by ajcasagrande** [comment]
@farshidtz The RTSP Auth server is new feature to the device service in 3.0 to password-protect the rtsp streams. You can configure the host and port [here](https://github.com/edgexfoundry/device-usb-camera/blob/main/cmd/res/configuration.yaml#L44).
