### ISSUE TITLE
Version API doesn't return the SDK version

### ISSUE THREAD

**Issue by lenny-goodell** [edgexfoundry-holding/device-usb-camera#35]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]
Version API

### Is this a regression?

No

### Description and Minimal Reproduction [**REQUIRED**]
Version API doesn't return the SDK version. Sample responses:
```
{
    "apiVersion": "v2",
    "version": "0.0.0",
    "serviceName": "device-onvif-camera",
    "sdk_version": "0.0.0"
}
```
The makefile here is missing the setting of the SDK version
https://github.com/edgexfoundry/device-usb-camera/blob/main/Makefile#L21
That is done here in other services:
https://github.com/edgexfoundry/app-service-configurable/blob/main/makefile#L20

Note this looks to be an issue will many or all the Go Devices and App services

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version [**REQUIRED**]:**

**Anything else relevant?**

**Comment by cloudxxx8** [comment]
For reference:
https://github.com/edgexfoundry/device-onvif-camera/pull/70
