### ISSUE TITLE
License of rtsp-simple-server missing from Docker image

### ISSUE THREAD

**Issue by farshidtz** [edgexfoundry-holding/device-usb-camera#53]
The docker image does not include the [license](https://github.com/aler9/rtsp-simple-server/blob/main/LICENSE) of rtsp-simple-server. Only the executable and configuration file are packaged:
https://github.com/edgexfoundry/device-usb-camera/blob/d52eed5e0bdf095fe71ab1c2620e174378e09b3d/Dockerfile#L36-L52

# 🐞 Bug Report

### Affected Services [**REQUIRED**]
Device USB Camera

### Is this a regression?
No

## 🌍  Your Environment
**Deployment Environment:**
Docker

**EdgeX Version [**REQUIRED**]:**
v0.0.1-dev.13

**Anything else relevant?**

**Comment by lenny-goodell** [comment]
@cloudxxx8 can your team address this one?
