### ISSUE TITLE
edgex USB Camera test

### ISSUE THREAD

**Issue by 018429** [edgexfoundry-holding/device-usb-camera#55]
For the edgex USB Camera test, Intel OAK is the only camera left. However, it is not a UVC camera and does not support regular video operations (via V4L2). I would like to know whether the current EDgex USB Camera device microservice can support this camera?

**Comment by lenny-goodell** [comment]
@018429 , Looks like `Intel OAK` is a a RealSense type of camera? if so, no the Device USB Camera service does not support RealSense cameras as they are much more complex than a simple USB camera and show up as multiple USB connects.

**Comment by ajcasagrande** [comment]
@018429 Advanced functionality such as that of `Intel RealSense` is currently not supported. _However, if you would like to just test the service out and have your camera act like a plain usb camera, you can try the following steps:_

<hr/>

Run `sudo dmesg -Hw` and then plug the camera in and see what messages appear. For my `Intel RealSense D435` I get the following output:

```
[Jul20 10:19] usb 2-1: new SuperSpeed USB device number 27 using xhci_hcd
[  +0.017363] usb 2-1: New USB device found, idVendor=8086, idProduct=0b07, bcdDevice=50.cf
[  +0.000015] usb 2-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  +0.000006] usb 2-1: Product: Intel(R) RealSense(TM) Depth Camera 435 
[  +0.000005] usb 2-1: Manufacturer: Intel(R) RealSense(TM) Depth Camera 435 
[  +0.000004] usb 2-1: SerialNumber: 829313021450
[  +0.005253] uvcvideo 2-1:1.1: Unknown video format 00000050-0000-0010-8000-00aa00389b71
[  +0.000107] usb 2-1: Found UVC 1.50 device Intel(R) RealSense(TM) Depth Camera 435  (8086:0b07)
[  +0.003712] input: Intel(R) RealSense(TM) Depth Ca as /devices/pci0000:00/0000:00:14.0/usb2/2-1/2-1:1.0/input/input151
[  +0.000958] uvcvideo 2-1:1.4: Unknown video format 36315752-1a66-a242-9065-d01814a8ef8a
[  +0.000018] usb 2-1: Found UVC 1.50 device Intel(R) RealSense(TM) Depth Camera 435  (8086:0b07)
```

When plugged in, you can run the command `v4l2-ctl --list-devices`, which for me produces: 
> Note: this command is part of the `v4l-utils` package
```
Intel(R) RealSense(TM) Depth Ca (usb-0000:00:14.0-1):
	/dev/video0
	/dev/video3
	/dev/video4
	/dev/video5
	/dev/video6
	/dev/video7
	/dev/media1
	/dev/media2
```

Using `ffplay`, I was able to determine `/dev/video6` provided a basic color video stream that is compatible with the `device-usb-camera` service. (Again, keep in mind this will be treated as a regular non-smart usb camera).

**Comment by 018429** [comment]
Run sudo dmesg -Hw and then plug the camera(OAK-D-Lite) in and I see these:
```
[7月21 13:57] usb 3-1: new high-speed USB device number 23 using xhci_hcd
[  +0.148567] usb 3-1: New USB device found, idVendor=03e7, idProduct=2485, bcdDevice= 0.01
[  +0.000009] usb 3-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  +0.000003] usb 3-1: Product: Movidius MyriadX
[  +0.000003] usb 3-1: Manufacturer: Movidius Ltd.
[  +0.000001] usb 3-1: SerialNumber: 03e72485
```
And I run the command ```v4l2-ctl --list-devices```,which for me preduces:
```
Unable to detect what device /dev/video0 is, exiting.
```

**Comment by ajcasagrande** [comment]
@018429 Yeah it looks like that device is only exposing the Movidius VPU to the host machine. Looking at their documentation and SDK, it looks like they only support communication with it via their custom XLink protocol.

https://github.com/luxonis/depthai-experiments/blob/master/gen2-rtsp-streaming/main.py#L61-L76

So like you said in your first message, it doesn't support any form of UVC or v4l2, which are required for the current implementation of this service.

**Comment by lenny-goodell** [comment]
Closing as answered
