### ISSUE TITLE
Device not register in edgex metadata after auto-discovery setup and console error.

### ISSUE THREAD

**Issue by surajitx-pal** [edgexfoundry-holding/device-usb-camera#64]
# 🐞 Bug Report
Rest API use to check device list.

curl -X GET http://localhost:59881/api/v2/device/all | jq .

**EdgeX Version [**REQUIRED**]:**
latest- from main branch, edgex-compose repo. V2.

**Anything else relevant?**

after some time ERROR logs in console -

level=INFO ts=2022-07-26T21:04:49.897574986Z app=device-usb-camera source=async.go:104 msg="Adding discovered device UVC_Camera_(046d_0825)-61C0AE50 to Metadata"
level=**ERROR** ts=2022-07-26T21:04:49.901876666Z app=device-usb-camera source=async.go:120 msg="failed to create discovered device UVC_Camera_(046d_0825)-61C0AE50: request failed, status code: 400, err: {\"apiVersion\":\"v2\",\"message\":\"AddDeviceRequest.Device.Name field only allows unreserved characters which are ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_~\",\"statusCode\":400}\n"
level=DEBUG ts=2022-07-26T21:04:49.902006461Z app=device-usb-camera source=async.go:127 msg="Filtered device addition finished"

**Comment by surajitx-pal** [comment]
Auto-discovery setup, services are up through Edgex Latest main branch(non secure mode). Device is discovered but not showing the device list through edgex command, and not in metadata device profile.

**Comment by lenny-goodell** [comment]
The device name `UVC_Camera_(046d_0825)-61C0AE50` has the `(` and `)` characters which are not valid for device names.

**Comment by lenny-goodell** [comment]
Look like the code here needs to include the open/close parenthesis
https://github.com/edgexfoundry/device-usb-camera/blob/fa6315a9dc6abe5875e1ce461ca165c4afc43fa4/internal/driver/device.go#L90-L93

[device.go](https://github.com/edgexfoundry/device-usb-camera/blob/fa6315a9dc6abe5875e1ce461ca165c4afc43fa4/internal/driver/device.go)
func buildDeviceName(cardName, serialNumber string) string {
    cardName = strings.ReplaceAll(strings.ReplaceAll(cardName, " ", "_"), ":", "_")
    serialNumber = strings.ReplaceAll(strings.ReplaceAll(serialNumber, ":", "_"), ".", "_")
    return fmt.Sprintf("%s-%s", cardName, serialNumber)
<https://github.com/[edgexfoundry/device-usb-camera](https://github.com/edgexfoundry/device-usb-camera)|edgexfoundry/device-usb-camera>edgexfoundry/device-usb-camera | Added by [GitHub](https://rsd-intel.slack.com/services/B020N2A516G)
